Retain comments and linebreaks when writting new yalm
f3ath/pubspec-version pull request #19
Opened 2019-06-07 20:43 UTC by Agraphie

Resolves #17 by parsing and updating version in place.

2019-06-13 18:56 UTC, f3ath commented
OK, so I discussed this with a friend. Yaml seems to be trickier than I though. For instance, what if the `version:` line has a comment in itself?

```yaml
version: 0.2.3 # lol parse me 
```

Or what if there is a multiline string?
```yaml
version: 0.2.3 # i am the version line
description: 'and I am a line with a
version: 3.2.1
in it'
```

I don't see an easy way to avoid using a real yaml parser.

2019-06-13 20:07 UTC, Agraphie commented
Yes good thought, you are right about that. But nothing a little regex can't fix. We just use a positive lookahead and match the version which is not contained in `"` or `'`. Then we non-greedely match until `#` to exclude any comments behind the version. I also included the things you mentioned in the test yaml.

2019-06-17 03:24 UTC, f3ath requested changes

2019-06-17 03:24 UTC, f3ath commented on test/pubspec_sample.yaml
> +version: 1.2.3
Is there a test checking this line is not getting changed?

2019-06-17 03:24 UTC, f3ath commented on lib/src/update_version.dart
> +        'version: "${oldVersion}"', "version: " + '"${newVersion.toString()}"');
I don't understand how different quotation is processed. This line seems to only deal with double quotes. Is there a test for double/single/no quotes?

2019-06-17 03:24 UTC, f3ath commented on lib/src/version_extractor.dart
> +abstract class VersionExtractor {
Why is it a class and why is the class abstract? A simple function would be enough.

2020-08-24 14:13 UTC, closed without merging